version: '3.4'

services:
  app:
    container_name: datadog-testapi
    build: .
    ports:
        - "5000:5000"
    volumes:
        - .:/code
        - testapi-logs:/var/log
    environment:
      - DD_AGENT_HOST=datadog-agent
    env_file:
      - ./environment/common.env
      - ./environment/testapi.env
    depends_on:
      - datadog-agent
    stdin_open: true
    tty: true
    command:
      - pipenv
      - run
      - ddtrace-run
      - gunicorn
      - --name="testapi"
      - --statsd-host=datadog-agent:8125
      - --bind=0.0.0.0:5000
      - testapi:app
    networks:
      - datadog

  datadog-agent:
    container_name: datadog-agent
    image: gcr.io/datadoghq/agent:latest
    ports:
      - "8126:8126"
      - "8125:8125"
    volumes:
      # PROMETHEUS METRICS
      - ./agent_conf/prometheus.d/conf.yaml:/etc/datadog-agent/conf.d/openmetrics.d/conf.yaml:ro
      # LOGGING[OPTION1]:config logging from file
      - ./agent_conf/python.d/conf.yml:/etc/datadog-agent/conf.d/python.d/conf.yml:ro
      - testapi-logs:/var/log/testapi:ro
      # LOGGING[OPTION2]: enable for logging based on containter autodiscovery
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#      - /proc/:/host/proc/:ro
#      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
#      - /etc/passwd:/etc/passwd:ro

    env_file:
      - ./environment/common.env
      - ./environment/datadog-agent.env
    environment:
#      - DD_SERVICE=datadog-agent
#      - DD_ENV=${DD_ENV}
      - DD_API_KEY=${DD_API_KEY}
    networks:
      - datadog

  locust:
    container_name: datadog-locust
    image: locustio/locust
    ports:
      - "8089:8089"
    depends_on:
      - app
      - datadog-agent
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://app:5000 --autostart
    networks:
      - datadog

  locust-worker:
    container_name: datadog-locust-worker
    image: locustio/locust
    depends_on:
      - locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host locust
    networks:
      - datadog

volumes:
  testapi-logs:

networks:
  datadog: