version: '3.4'

services:
  app:
    build: .
    ports:
        - "5000:5000"
    volumes:
        - .:/code
    environment:
      - DD_SERVICE=testapi
      - DD_ENV=dev
      - DD_VERSION=0.1
      - DD_AGENT_HOST=datadog-agent
      - FLASK_DEBUG=False
    depends_on:
      - datadog-agent
    stdin_open: true
    tty: true
    command:
      - pipenv
      - run
      - ddtrace-run
      - gunicorn
      - --bind=0.0.0.0:5000
      - app:app

  datadog-agent:
    image: gcr.io/datadoghq/agent:latest
    ports:
      - 8126:8126
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_APM_ENABLED=true
      - DD_SITE=datadoghq.eu
      - DD_ENV="dev"